const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const root = path.resolve(__dirname, '../../..');
const publicRoot = path.join(root, 'apps/frontend/public');

test('home integra categorias ao mapa e aplica cores aos marcadores', () => {
  const vue = fs.readFileSync(path.join(publicRoot, 'vue-app.js'), 'utf8');
  const categories = fs.readFileSync(path.join(publicRoot, 'home-categories.js'), 'utf8');
  const index = fs.readFileSync(path.join(publicRoot, 'index.html'), 'utf8');

  assert.match(vue, /categoriaMapa = ref\('\'\)/);
  assert.match(vue, /imoveisDoMapa = computed/);
  assert.match(vue, /L\.divIcon/);
  assert.match(vue, /--marker-color/);
  assert.match(vue, /const buscar = \(\) =>/);
  assert.doesNotMatch(vue.match(/const buscar = \(\) =>[\s\S]*?location\.href/)?.[0] || '', /await geocodificar/);
  assert.match(vue, /item\.bairro/);
  assert.match(vue, /\(jd\|jard\)/);
  assert.match(vue, /makeUrl\(query, 'place', 5\)/);
  assert.match(vue, /Cidade/);
  assert.match(vue, /feature\.place_type\?\.includes\('place'\) \? 12 : 15/);
  assert.match(vue, /Home\.template = Home\.template\.replace\('<p class="home-kicker">Explore Tatuí<\/p><h2>Imóveis no mapa<\/h2>', '<h2>Explore Tatuí<\/h2>'\)/);
  assert.match(vue, /Veja os imóveis disponíveis em Tatuí e encontre o seu próximo endereço/);
  assert.match(vue, /Home\.template = Home\.template\.replace\('<p>Veja os imóveis disponíveis em Tatuí e encontre o seu próximo endereço\.<\/p>', ''\)/);
  assert.match(categories, /home-map-categories/);
  assert.match(categories, /Selecione uma categoria/);
  assert.match(categories, /__homeSetCategory/);
  assert.match(categories, /Limpar categoria/);
  assert.match(categories, /querySelector\('\.home-search'\)/);
  assert.match(categories, /home-map-category-controls/);
  assert.doesNotMatch(categories, /home-map-category-help/);
  assert.match(categories, /search\?\.remove\(\)/);
  assert.match(categories, /explorer\.append\(map\)/);
  assert.match(categories, /sectionHeading\.append\(panel\)/);
  const styles = fs.readFileSync(path.join(publicRoot, 'react.css'), 'utf8');
  assert.match(styles, /home-map-category-button span \{[^}]*font-size:12px;[^}]*position:static/);
  assert.match(styles, /home-map-category-button strong \{[^}]*width:48px; height:48px/);
  assert.match(styles, /home-map-categories \.home-map-filter-heading \{ text-align:center; \}/);
  assert.match(styles, /home-map-categories h3 \{ font:650 18px/);
  assert.match(styles, /home-map-categories \{ grid-template-columns:1fr auto 1fr; }/);
  assert.match(styles, /home-map-explorer \.home-map \{ grid-row:2\/4; }/);
  assert.match(styles, /home-map-categories \.home-category-clear \{[^}]*grid-column:3/);
  assert.match(styles, /home-map-explorer \.home-search.*grid-row:3/);
  assert.match(styles, /home-map-explorer \.home-map.*grid-row:4/);
  assert.match(styles, /home-section-copy \{ align-items:center; display:flex; grid-column:1; grid-row:1/);
  assert.match(styles, /home-map-categories \{ align-items:center; background:transparent; display:flex; flex-direction:column/);
  assert.match(styles, /home-all-properties-card \{[^}]*grid-column:2; grid-row:3/);
  assert.match(styles, /home-map-section \.home-all-properties-card \{ grid-column:1; grid-row:4/);
  assert.match(styles, /home-map-section \.home-announce-card \{ grid-column:1; grid-row:5; margin-top:16px; \}/);
  assert.match(styles, /home-map-section \.home-announce-button \{ display:flex; justify-content:center/);
  assert.match(index, /<script src="home-categories\.js"><\/script>/);
});

test('popup do mapa evita repetir categoria/transação e destaca etiquetas, valor e ação', () => {
  const vue = fs.readFileSync(path.join(publicRoot, 'vue-app.js'), 'utf8');
  const styles = fs.readFileSync(path.join(publicRoot, 'react.css'), 'utf8');
  const start = vue.indexOf('const popup = item =>');
  const end = vue.indexOf('const desenharMarcadores', start);
  const popup = vue.slice(start, end);
  assert.ok(start >= 0 && end > start, 'map popup renderer exists');
  assert.match(popup, /PropertyOffers\.displayTitle\(item\)/);
  assert.match(popup, /PropertyOffers\.parse\(item\)/);
  assert.match(popup, /react-popup-tag/);
  assert.match(popup, /Aceita permuta/);
  assert.match(popup, /react-popup-price/);
  assert.match(popup, /Ver detalhes/);
  assert.doesNotMatch(popup, /item\.titulo|money\(item\)/);
  assert.match(styles, /\.react-popup-tags\s*\{/);
  assert.match(styles, /\.react-popup-price\s*\{/);
  assert.match(styles, /\.react-popup \.react-popup-action\s*\{/);
});
